### ISSUE TITLE
Not Getting The Same Results

### ISSUE THREAD

**Issue by KhiemPhi** [suyz526/ZebraPose#10]
Hi all, I was trying to re-run your baseline results using the provided checkpoints on the LMO dataset. What I found is that the results were closer to V1 of your paper. I even tried to change the resize methods in inference but it's not giving me the same results. Can someone help me on this?

**Comment by suyz526** [comment]
Hi,

Would you please provide more details, which checkpoint file and config file you have used (from which folder)?

**Comment by KhiemPhi** [comment]
I figured out my issue, it seems that if I increased the number of neighborhood points in the Progessive-X solver I was able to reproduce the results.
