### ISSUE TITLE
CUDA out of memory (on 16GB GPU with minimal batch size)

### ISSUE THREAD

**Issue by ThijsvdBurg** [suyz526/ZebraPose#14]
Dear authors,

Thank you for your contribution and work.

I am trying to run your code for my own research. However, CUDA keeps running out of memory. 
I have tried to make the following modifications, some have some effect of the memory running out a bit slower:
- Set the batch size to 2 (it will not go to 1) 
- Set resnet to 18 layers
- Switched to Google Colab (16GB GPU instead of the 4GB on my computer)
- Switched progressive-x off.

I am trying to train on a small subset of TUD-L dataset, using the GTs and pre-trained backbones provided through the links on this repo.

Here is a screenshot from the Colab environment:

![Screenshot 2022-10-25 at 16 08 58](https://user-images.githubusercontent.com/28752784/197799592-ad4f8352-1333-4775-a096-0c8646c261d6.png)

Suddenly, there is a huge spike in GPU RAM usage, seen on the right in the dashboard.

Is this an issue or is this expected behaviour? Your help would be much appreciated.

Best regards,
Thijs

**Comment by suyz526** [comment]
Hi, 

Thanks for your interest! I guess you used a configuration file which contains a Efficient net key, in this case, it will always use efficient net as backbone.

We could have put some code to avoid this. Sorry for the inconvenience.

Best, 
Yongzhi

**Comment by ThijsvdBurg** [comment]
Dear Yongzhi,

Thank you for the very quick reply. Indeed, not using EfficientNet solved the problem for me. The reason that I tried running with EfficientNet is that the code did not accept the omission of an EfficientNet key in the config file, so the default config of using a config/config_BOP/tudl/ file was giving the following error:

```
Traceback (most recent call last):
  File "/home/pmvanderburg/noetic-husky/bop_ros_ws/src/ZebraPose/zebrapose/train.py", line 404, in <module>
    main(configs)
  File "/home/pmvanderburg/noetic-husky/bop_ros_ws/src/ZebraPose/zebrapose/train.py", line 195, in main
    efficientnet_key = efficientnet_key
UnboundLocalError: local variable 'efficientnet_key' referenced before assignment
```

**Comment by suyz526** [comment]
Dear Thijs,

thanks for finding out this issue. I think I forget to add the `else`
for this [if statement](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/zebrapose/train.py#L58).
It should be  `else: efficientnet_key=None`.

We plan to make a full test later this year.

Best,
Yongzhi
