### ISSUE TITLE
Expected to get a single numpy array of shape (H,W) or (H,W,C) 

### ISSUE THREAD

**Issue by hansaskov** [suyz526/ZebraPose#15]
Hello. I am trying out zebrapose and I'm having some issues when training on the example given in the readme.

I get this error 

Neighborhood calculation time = 0.243874 secs.
Neighborhood calculation time = 0.249840 secs.
Neighborhood calculation time = 0.193178 secs.
Neighborhood calculation time = 0.205201 secs.
Neighborhood calculation time = 0.230796 secs.
Neighborhood calculation time = 0.317984 secs.
Neighborhood calculation time = 0.238225 secs.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [02:52<00:00,  7.83s/it]
ADD_passed 0.0
best_score 0.0
best check point saved in  /home/robotlab/Desktop/HAOV/ZebraPose/6dof_pose_experiments/experiments/checkpoints/exp_lmo_BOPape/best_score/0_0000step0
exp_lmo_BOP  iteration_step: 1 loss_b: 0.7003157009678205 loss_m: 0.4887707233428955 loss: 2.589717826246357
exp_lmo_BOP  iteration_step: 2 loss_b: 0.69137206054109 loss_m: 0.3945087790489197 loss: 2.46862496067219
exp_lmo_BOP  iteration_step: 3 loss_b: 0.694508611202345 loss_m: 0.31038543581962585 loss: 2.3939112694266607
exp_lmo_BOP  iteration_step: 4 loss_b: 0.6951448561501329 loss_m: 0.2788199484348297 loss: 2.3642545168852283
exp_lmo_BOP  iteration_step: 5 loss_b: 0.6913055153449651 loss_m: 0.22996273636817932 loss: 2.3038792824030745
exp_lmo_BOP  iteration_step: 6 loss_b: 0.6898123773388913 loss_m: 0.25095099210739136 loss: 2.320388124124065
exp_lmo_BOP  iteration_step: 7 loss_b: 0.6898932232178236 loss_m: 0.22556562721729279 loss: 2.295245296870764
exp_lmo_BOP  iteration_step: 8 loss_b: 0.689580717264042 loss_m: 0.21235992014408112 loss: 2.281102071936207
exp_lmo_BOP  iteration_step: 9 loss_b: 0.6850530220622502 loss_m: 0.20650124549865723 loss: 2.2616603116854077
exp_lmo_BOP  iteration_step: 10 loss_b: 0.6861161840507828 loss_m: 0.19408346712589264 loss: 2.252432019278241
exp_lmo_BOP  iteration_step: 11 loss_b: 0.685705219347128 loss_m: 0.19636832177639008 loss: 2.253483979817774
exp_lmo_BOP  iteration_step: 12 loss_b: 0.6799169770450811 loss_m: 0.19241726398468018 loss: 2.2321681951199235
exp_lmo_BOP  iteration_step: 13 loss_b: 0.6819430279221167 loss_m: 0.18748752772808075 loss: 2.233316611494431
exp_lmo_BOP  iteration_step: 14 loss_b: 0.6840540645380042 loss_m: 0.18512609601020813 loss: 2.237288289624221
Traceback (most recent call last):
  File "train.py", line 383, in <module>
    main(configs)
  File "train.py", line 225, in main
    for batch_idx, (data, entire_masks, masks, Rs, ts, Bboxes, class_code_images, cam_Ks) in enumerate(train_loader):
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robotlab/Desktop/HAOV/ZebraPose/zebrapose/bop_dataset_pytorch.py", line 263, in __getitem__
    x = self.apply_augmentation(x)
  File "/home/robotlab/Desktop/HAOV/ZebraPose/zebrapose/bop_dataset_pytorch.py", line 351, in apply_augmentation
    x = augmentations.augment_image(x)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 763, in augment_image
    "Expected to get a single numpy array of shape (H,W) or (H,W,C) "
TypeError: %d format: a number is required, not str

The config is the same as "exp_lmo_BOP.txt" but because i have a 2080Ti with 11GB of vram i have chosen my number of workers to 4 using a batch size of 16.

I believe my file structure is correct, but I'm not entirely sure. Here it is for lmo. 
![Screenshot from 2022-10-26 13-53-04](https://user-images.githubusercontent.com/70580312/198019398-f92073b5-e3a4-435c-8321-96ea43efb214.png)

Any ideas as to what might cause this?

**Comment by lyltc1** [comment]
From the imformation you provided,
`File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 763, in augment_image
"Expected to get a single numpy array of shape (H,W) or (H,W,C) "
TypeError: %d format: a number is required, not str`
1. Maybe the problem is the version of imgaug, you can try use version 0.4.0.
2. If 1. can not solve the problem, can you please show x around
`File "/home/robotlab/Desktop/HAOV/ZebraPose/zebrapose/bop_dataset_pytorch.py", line 351, in apply_augmentation
x = augmentations.augment_image(x)`

**Comment by hansaskov** [comment]
Thank you for the quick response. I appreciate your time

1. My version of imgaug is already 0.4.0 which is the latest version as of 2020. 

2. I added the following to the code. 

![Screenshot from 2022-10-26 15-35-50](https://user-images.githubusercontent.com/70580312/198040560-99428234-5a14-4455-b029-7a70d3d2065d.png)

Here is the output  
...
  [196 206 206]
  [199 209 209]
  [204 214 214]]

 [[198 206 206]
  [198 206 206]
  [196 204 204]
  ...
  [208 218 218]
  [208 218 218]
  [209 219 219]]]
Shape (480, 640, 3)
[[[154 166 148]
  [149 161 143]
  [150 162 144]
  ...
  [182 193 177]
  [181 192 176]
  [180 191 175]]

 [[150 162 144]
  [150 162 144]
  [153 165 147]
  ...
  [185 196 180]
  [188 199 183]
  [188 199 183]]

 [[151 163 145]
  [146 158 140]
  [145 157 139]
  ...
  [187 197 181]
  [187 197 181]
  [184 194 178]]

 ...

 [[180 190 173]
  [180 190 173]
  [172 182 165]
  ...
  [241 243 237]
  [241 243 237]
  [243 245 239]]

 [[168 178 161]
  [172 182 165]
  [172 182 165]
  ...
  [240 242 236]
  [240 242 236]
  [243 245 239]]

 [[173 183 166]
  [172 182 165]
  [170 180 163]
  ...
  [239 241 235]
  [240 242 236]
  [243 245 239]]]
exp_lmo_BOP  iteration_step: 7 loss_b: 0.6844710770915593 loss_m: 0.22522315382957458 loss: 2.2786363851042526
Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main(configs)
  File "train.py", line 225, in main
    for batch_idx, (data, entire_masks, masks, Rs, ts, Bboxes, class_code_images, cam_Ks) in enumerate(train_loader):
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/robotlab/Desktop/HAOV/ZebraPose/zebrapose/bop_dataset_pytorch.py", line 263, in __getitem__
    x = self.apply_augmentation(x)
  File "/home/robotlab/Desktop/HAOV/ZebraPose/zebrapose/bop_dataset_pytorch.py", line 353, in apply_augmentation
    x = augmentations.augment_image(x)
  File "/home/robotlab/mambaforge/envs/zebrapose/lib/python3.8/site-packages/imgaug/augmenters/meta.py", line 763, in augment_image
    "Expected to get a single numpy array of shape (H,W) or (H,W,C) "
TypeError: %d format: a number is required, not str

**Comment by hansaskov** [comment]
Accidentally closed the issue.

**Comment by hansaskov** [comment]
Accidentally closed the issue

**Comment by lyltc1** [comment]
I am sorry for this problem but we can not reproduce it in our computer.
Maybe you can try:
1. change the number of worker to 0 (which make the debug easier)
2. write code like `try ... except ...` to show the image path when the program broken, then check the image by yourself.

**Comment by hansaskov** [comment]
Thank you for the answer.  

As i suspected the value of x didn't get enough time to print out. I therefore added a delay of 0.5 after the print out.

The value of x is not defined
The print returns :
    Shape ()
    None

I would like to see your installed packages can you run `pip list` of your inviroment?

Here is mine
----------------------- ----------- -------------------------------------------------------
absl-py                 1.3.0
bop-toolkit-lib         1.0         /home/robotlab/Desktop/HAOV/ZebraPose/bop_toolkit
cachetools              5.2.0
certifi                 2022.9.24
charset-normalizer      2.1.1
contourpy               1.0.5
cycler                  0.11.0
Cython                  0.29.24
fonttools               4.38.0
freetype-py             2.3.0
glumpy                  1.1.0
google-auth             2.13.0
google-auth-oauthlib    0.4.6
grpcio                  1.50.0
hsluv                   5.0.3
idna                    3.4
imageio                 2.5.0
imgaug                  0.4.0
importlib-metadata      5.0.0
kiwisolver              1.3.1
Markdown                3.4.1
MarkupSafe              2.1.1
matplotlib              3.6.1
networkx                2.8.7
numpy                   1.23.4
oauthlib                3.2.2
opencv-python           4.3.0.36
packaging               21.3
pandas                  1.5.1
Pillow                  9.2.0
pip                     22.3
protobuf                3.19.6
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0
PyOpenGL                3.1.0
pyparsing               3.0.9
pypng                   0.0.19
pyprogressivex          0.1         /home/robotlab/Desktop/HAOV/ZebraPose/progressive-x/src
python-dateutil         2.8.2
pytz                    2022.5
PyWavelets              1.4.1
requests                2.28.1
requests-oauthlib       1.3.1
rsa                     4.9
scikit-image            0.19.3
scipy                   1.5.1
setuptools              59.5.0
Shapely                 1.8.5.post1
six                     1.16.0
tensorboard             2.10.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tifffile                2022.10.10
torch                   1.10.1
torch-tb-profiler       0.4.0
torchaudio              0.10.1
torchvision             0.11.2
tqdm                    4.64.1
triangle                20190115.2
typing_extensions       4.4.0
urllib3                 1.26.12
vispy                   0.11.0
Werkzeug                2.2.2
wheel                   0.37.1
zipp                    3.10.0

**Comment by lyltc1** [comment]
Package                 Version      Location
----------------------- ------------ -------------------------------------
absl-py                 1.1.0
addict                  2.4.0
anyio                   3.6.1
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
asttokens               2.0.5
attrs                   21.4.0
Babel                   2.10.1
backcall                0.2.0
beautifulsoup4          4.11.1
bleach                  5.0.0
bop-toolkit-lib         1.0          /home/lyltc/git/ZebraPose/bop_toolkit
cachetools              5.2.0
certifi                 2022.5.18.1
cffi                    1.15.0
chardet                 4.0.0
charset-normalizer      2.0.12
cycler                  0.11.0
cyglfw3                 3.1.0.2
Cython                  0.29.24
debugpy                 1.6.0
decorator               5.1.1
defusedxml              0.7.1
deprecation             2.1.0
entrypoints             0.4
executing               0.8.3
fastjsonschema          2.15.3
filterpy                1.4.5
fonttools               4.33.3
freetype-py             2.3.0
glcontext               2.3.6
glfw                    1.12.0
glumpy                  1.1.0
google-auth             2.9.0
google-auth-oauthlib    0.4.6
grpcio                  1.47.0
hsluv                   5.0.3
idna                    3.3
imageio                 2.5.0
imageio-ffmpeg          0.4.7
imgaug                  0.4.0
importlib-metadata      4.11.4
importlib-resources     5.7.1
ipykernel               6.13.1
ipython                 8.4.0
ipython-genutils        0.2.0
ipywidgets              7.7.0
jedi                    0.18.1
Jinja2                  3.1.2
joblib                  1.1.0
json5                   0.9.8
jsonschema              4.6.0
jupyter-client          7.3.3
jupyter-core            4.10.0
jupyter-packaging       0.12.1
jupyter-server          1.17.1
jupyterlab              3.4.3
jupyterlab-pygments     0.2.2
jupyterlab-server       2.14.0
jupyterlab-widgets      1.1.0
k-means-constrained     0.7.0
kiwisolver              1.3.1
llvmlite                0.39.0
Markdown                3.3.7
MarkupSafe              2.1.1
matplotlib              3.1.3
matplotlib-inline       0.1.3
mistune                 0.8.4
mmcv                    1.5.2
moderngl                5.7.0        /home/lyltc/git/moderngl
moderngl-window         2.4.2
multipledispatch        0.6.0
nbclassic               0.3.7
nbclient                0.6.4
nbconvert               6.5.0
nbformat                5.4.0
nest-asyncio            1.5.5
networkx                2.8.3
notebook                6.4.12
notebook-shim           0.1.0
numba                   0.56.0
numpy                   1.23.2
oauthlib                3.2.0
open3d                  0.15.2
opencv-python           4.6.0.66
ortools                 9.0.9048
packaging               21.3
pandas                  1.4.2
pandocfilters           1.5.0
parso                   0.8.3
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.2.0
Pillow-SIMD             9.0.0.post1
pip                     21.2.4
prometheus-client       0.14.1
prompt-toolkit          3.0.29
protobuf                3.19.4
psutil                  5.9.1
ptyprocess              0.7.0
pure-eval               0.2.2
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyassimp                4.1.3
pycocotools             2.0
pycparser               2.21
PyDistMesh              1.2
pyglet                  2.0a4
Pygments                2.12.0
pymeshlab               2022.2.post2
pymunk                  6.2.1
PyOpenGL                3.1.6
pyparsing               3.0.9
pypng                   0.0.19
pyprogressivex          0.1          /home/lyltc/git/progressive-x/src
PyQt5                   5.15.7
PyQt5-Qt5               5.15.2
PyQt5-sip               12.11.0
pyquaternion            0.9.9
pyrr                    0.10.3
pyrsistent              0.18.1
PySDL2                  0.9.14
PySide2                 5.15.2.1
python-dateutil         2.8.2
pytz                    2022.1
PyWavefront             1.3.3
PyWavelets              1.3.0
PyYAML                  6.0
pyzmq                   23.1.0
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-image            0.19.2
scikit-learn            1.1.1
scipy                   1.9.0
seaborn                 0.11.2
Send2Trash              1.8.0
setuptools              61.2.0
Shapely                 1.8.2
shiboken2               5.15.2.1
six                     1.16.0
sniffio                 1.2.0
soupsieve               2.3.2.post1
stack-data              0.2.0
tensorboard             2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               1.1.0
terminado               0.15.0
threadpoolctl           3.1.0
tifffile                2022.5.4
tinycss2                1.1.1
tomlkit                 0.11.0
torch                   1.8.1+cu111
torchaudio              0.8.1
torchvision             0.9.1+cu111
tornado                 6.1
tqdm                    4.64.0
traitlets               5.2.2.post1
transforms3d            0.3.1
triangle                20190115.2
trimesh                 3.15.1
typing_extensions       4.2.0
urllib3                 1.26.9
vispy                   0.10.0
wcwidth                 0.2.5
webencodings            0.5.1
websocket-client        1.3.2
Werkzeug                2.1.2
wheel                   0.37.1
widgetsnbextension      3.6.0
yapf                    0.32.0
zipp                    3.8.0

**Comment by suyz526** [comment]
> Thank you for the answer.
> 
> As i suspected the value of x didn't get enough time to print out. I therefore added a delay of 0.5 after the print out.
> 
> The value of x is not defined The print returns : Shape () None
> 
> I would like to see your installed packages can you run `pip list` of your inviroment?
> 
> Here is mine
> 
> absl-py 1.3.0 bop-toolkit-lib 1.0 /home/robotlab/Desktop/HAOV/ZebraPose/bop_toolkit cachetools 5.2.0 certifi 2022.9.24 charset-normalizer 2.1.1 contourpy 1.0.5 cycler 0.11.0 Cython 0.29.24 fonttools 4.38.0 freetype-py 2.3.0 glumpy 1.1.0 google-auth 2.13.0 google-auth-oauthlib 0.4.6 grpcio 1.50.0 hsluv 5.0.3 idna 3.4 imageio 2.5.0 imgaug 0.4.0 importlib-metadata 5.0.0 kiwisolver 1.3.1 Markdown 3.4.1 MarkupSafe 2.1.1 matplotlib 3.6.1 networkx 2.8.7 numpy 1.23.4 oauthlib 3.2.2 opencv-python 4.3.0.36 packaging 21.3 pandas 1.5.1 Pillow 9.2.0 pip 22.3 protobuf 3.19.6 pyasn1 0.4.8 pyasn1-modules 0.2.8 pycocotools 2.0 PyOpenGL 3.1.0 pyparsing 3.0.9 pypng 0.0.19 pyprogressivex 0.1 /home/robotlab/Desktop/HAOV/ZebraPose/progressive-x/src python-dateutil 2.8.2 pytz 2022.5 PyWavelets 1.4.1 requests 2.28.1 requests-oauthlib 1.3.1 rsa 4.9 scikit-image 0.19.3 scipy 1.5.1 setuptools 59.5.0 Shapely 1.8.5.post1 six 1.16.0 tensorboard 2.10.1 tensorboard-data-server 0.6.1 tensorboard-plugin-wit 1.8.1 tifffile 2022.10.10 torch 1.10.1 torch-tb-profiler 0.4.0 torchaudio 0.10.1 torchvision 0.11.2 tqdm 4.64.1 triangle 20190115.2 typing_extensions 4.4.0 urllib3 1.26.12 vispy 0.11.0 Werkzeug 2.2.2 wheel 0.37.1 zipp 3.10.0

Hi!

Since x has no shape, I assume that that image is missing in the folder. Could you please have a check?
