### ISSUE TITLE
Error building "Generate_Mesh_with_GT_Color"

### ISSUE THREAD

**Issue by hansaskov** [suyz526/ZebraPose#16]
When building "Binary_Code_GT_Generator/Generate_Mesh_with_GT_Color" i received a lot of errors. 

I fixed the issue by  changing the required c++ version from "-std=c++11" to  "-std=c++14"  In this cmake file https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_Mesh_with_GT_Color/CMakeLists.txt

Is this correct?

**Comment by suyz526** [comment]
Hi,

I think this C++ code is very sensitive to the PCL version. Which PCL version are you using? 

Pasting the error log here would also be helpful.

If you only want to use the ICP refinement, you don't need to build this one. You will only need to build the rendering code.

**Comment by suyz526** [comment]
You can also visualize the mesh with the one that I provided for BOP datasets. If the color is similar, I think it should be correct.

**Comment by hansaskov** [comment]
To be clear. My build finished correctly after i changed the c++ standard library version to 14.

I am using PCL version 1.12.1

Here is the error log when building using c++ 11
I will omit most of the error log since it has reached my console line limit

....
/usr/include/c++/11/bits/stl_algobase.h:2069:14:   required from ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<const pcl::PCLPointField*, std::vector<pcl::PCLPointField> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)> >]’
/usr/include/c++/11/bits/stl_algobase.h:2114:23:   required from ‘_Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = __gnu_cxx::__normal_iterator<const pcl::PCLPointField*, std::vector<pcl::PCLPointField> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)> >]’
/usr/include/c++/11/bits/stl_algo.h:3910:28:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = __gnu_cxx::__normal_iterator<const pcl::PCLPointField*, std::vector<pcl::PCLPointField> >; _Predicate = pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)>]’
/usr/include/pcl-1.12/pcl/common/io.h:63:37:   required from here
/usr/include/c++/11/bits/predefined_ops.h:318:30: error: no match for call to ‘(pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)>) (const pcl::PCLPointField&)’
  318 |         { return bool(_M_pred(*__it)); }
      |                       ~~~~~~~^~~~~~~
In file included from /usr/include/pcl-1.12/pcl/filters/filter.h:43,
                 from /usr/include/pcl-1.12/pcl/filters/filter_indices.h:42,
                 from /usr/include/pcl-1.12/pcl/filters/extract_indices.h:42,
                 from /home/robotlab/Desktop/HAOV/ZebraPose/Binary_Code_GT_Generator/Generate_Mesh_with_GT_Color/Generate_Mesh_with_GT_Color.cpp:11:
/usr/include/pcl-1.12/pcl/common/io.h:64:9: note: candidate: ‘pcl::getFieldIndex(const pcl::PCLPointCloud2&, const string&)::<lambda(int)>’
   64 |         [&field_name](const auto field) { return field.name == field_name; });
      |         ^
/usr/include/pcl-1.12/pcl/common/io.h:64:9: note:   no known conversion for argument 1 from ‘const pcl::PCLPointField’ to ‘int’
In file included from /usr/include/c++/11/functional:59,
                 from /usr/include/pcl-1.12/pcl/type_traits.h:45,
                 from /usr/include/pcl-1.12/pcl/memory.h:46,
                 from /usr/include/pcl-1.12/pcl/io/obj_io.h:39,
                 from /home/robotlab/Desktop/HAOV/ZebraPose/Binary_Code_GT_Generator/Generate_Mesh_with_GT_Color/Generate_Mesh_with_GT_Color.cpp:4:
/usr/include/c++/11/bits/std_function.h: At global scope:
/usr/include/c++/11/bits/std_function.h:435:9: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor&&) [with _Functor = pcl::io::ply::ply_parser::<lambda(const string&, std::size_t)>::<lambda()>; _Constraints = void; _Res = void; _ArgTypes = {}]’, declared using local type ‘pcl::io::ply::ply_parser::<lambda(const string&, std::size_t)>::<lambda()>’, is used but never defined [-fpermissive]
  435 |         function(_Functor&& __f)
      |         ^~~~~~~~
/usr/include/c++/11/bits/std_function.h:435:9: error: ‘std::function<_Res(_ArgTypes ...)>::function(_Functor&&) [with _Functor = pcl::io::ply::ply_parser::<lambda(const string&, std::size_t)>::<lambda()>; _Constraints = void; _Res = void; _ArgTypes = {}]’, declared using local type ‘pcl::io::ply::ply_parser::<lambda(const string&, std::size_t)>::<lambda()>’, is used but never defined [-fpermissive]
make[2]: *** [CMakeFiles/Generate_Mesh_with_GT_Color.dir/build.make:76: CMakeFiles/Generate_Mesh_with_GT_Color.dir/Generate_Mesh_with_GT_Color.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Generate_Mesh_with_GT_Color.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by hansaskov** [comment]
I will close the issue as the build did complete

**Comment by suyz526** [comment]
The errors are related to PCL. The C++ code in Zebrapose only used mesh loading and writing API from PCL. The critical k-means part will be processed by opencv. 

I guess PCL 1.12 used new features from C++, which requires C++14.

And I think your solution is correct.
