### ISSUE TITLE
OpenGL shader issue when generating GT training data

### ISSUE THREAD

**Issue by ThijsvdBurg** [suyz526/ZebraPose#17]
Dear Yongzhi,

I have compiled and installed the GT generation part of the code and dependencies.
The GT object mesh is successfully generated, but I am running into an error when trying to render the GT training data.

I changed the line 39 in the opengl_render.cpp to my local path to the render_related_source folder.
It happens on both my own dataset and on LM-O.

I also noticed that this portion of the code received major updates 15 days ago. Is this a working version on your system?

Below is the resulting output.

```
$ python generate_training_labels_for_BOP.py --bop_path $BOP_PATH --dataset_name lmo --force_rewrite True --is_training_data True --data_folder train --start_obj_id 1 --end_obj_id 1
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000001.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000005.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000006.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000008.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000009.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000010.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000011.ply
/media/pmvanderburg/T71/bop_datasets/lmo/models/obj_000012.ply
if models are not fully listed above, please make sure there are ply files available
[640.      480.      572.4114  573.57043 325.2611  242.04899]
ERROR::SHADER::FILE_NOT_SUCCESFULLY_READ
ERROR::SHADER_COMPILATION_ERROR of type: VERTEX
0:1(1): error: syntax error, unexpected $end

 -- --------------------------------------------------- -- 
ERROR::SHADER_COMPILATION_ERROR of type: FRAGMENT
0:1(1): error: syntax error, unexpected $end

 -- --------------------------------------------------- -- 
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
 -- --------------------------------------------------- -- 
```

Can you maybe point me in the right direction?

Best,
Thijs

**Comment by ThijsvdBurg** [comment]
I think I have found an error on my side. I will get back to this later today or tomorrow!

**Comment by ThijsvdBurg** [comment]
So apparently I changed the path in [line 39](https://github.com/ThijsvdBurg/ZebraPose/blob/395f869d0e235eebbeccc3316dd54ad69722f714/Binary_Code_GT_Generator/Render_GT_Color_Mesh_to_GT_Img/render_related_source/opengl_render.cpp#L39) but I didn't check whether is was correct. 
It seems to be working now since during the rendering, it shows the surface encoded mesh renders in the window. However, the resulting images are all black and do not contain the rendered GT object.

**Comment by suyz526** [comment]
Hi Thijs,

The recent update added a function to get the rendered depth required for ICP. And the code works on Ubuntu 18.04.

I also have met some trouble when I use the code on Ubuntu 22.04. My solution was removing [L185 to L187](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/Binary_Code_GT_Generator/Render_GT_Color_Mesh_to_GT_Img/render_related_source/opengl_render.cpp#L185). 

And compile the C++ code again. I hope this also work for you.

Best,
Yongzhi
