### ISSUE TITLE
Run test.py, it raise No module named 'Render'

### ISSUE THREAD

**Issue by Arrebol2020** [suyz526/ZebraPose#21]
Hi, I want to run test.py with ycbv data, I use (resnet): 
```
python test.py --cfg config/config_BOP/lmo/exp_ycbv_BOP.txt --obj_name banana --ckpt_file xxx/checkpoint --ignore_bit 0 --eval_output_path xxx/report
```
![image](https://user-images.githubusercontent.com/43379773/211140031-9911445c-a363-4bb9-83f0-fe8aa1edf616.png)

it will raise `no module named 'Render'` in ICP_Render.py line 1

**Comment by suyz526** [comment]
Hi, 

The 3D refinement needs the Render module. You can install it according to Step 2 in this [doc](https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_GT.md).

If the 3D refinement with depth image is unnecessary for you, You can also change all `if configs['use_icp']` as `if False`, so that the inference only uses RGB image.

Best,
Yongzhi

**Comment by Arrebol2020** [comment]
> 

Hi, follow this [doc](https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_GT.md) I successed install the Render use pip install -e ., but when I run test.py, it raise:
```
test dataset
150
Failed to create GLFW window
bind  /home/Arrebol/projs/ZebraPose/data/ycbv/models/obj_000010.ply  to the render buffer position 0
Segmentation fault
```
I'm not sure if it's because I closed the server's visual interface or I didn't install the Render correctly.

**Comment by Arrebol2020** [comment]
> Hi,
> 
> The 3D refinement needs the Render module. You can install it according to Step 2 in this [doc](https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_GT.md).
> 
> If the 3D refinement with depth image is unnecessary for you, You can also change all `if configs['use_icp']` as `if False`, so that the inference only uses RGB image.
> 
> Best, Yongzhi

Hi, follow this [doc](https://github.com/suyz526/ZebraPose/blob/main/Binary_Code_GT_Generator/Generate_GT.md) I successed install the Render use pip install -e ., but when I run test.py, it raise:
```
test dataset
150
Failed to create GLFW window
bind  /home/Arrebol/projs/ZebraPose/data/ycbv/models/obj_000010.ply  to the render buffer position 0
Segmentation fault
```
I'm not sure if it's because I closed the server's visual interface or I didn't install the Render correctly.

**Comment by suyz526** [comment]
Hi, 

As far as I know, GLFW does not support offscreen rendering. That means you need a GUI.

You can also do the refinement step totally separately.  More specifically, you can run the network inference, and save the predicted pose as well as the object mask. And then run the refinement on another machine, which has a GUI. The refinement step only requires CPU.


Best,
Yongzhi

**Comment by Arrebol2020** [comment]
> Hi,
> 
> As far as I know, GLFW does not support offscreen rendering. That means you need a GUI.
> 
> You can also do the refinement step totally separately. More specifically, you can run the network inference, and save the predicted pose as well as the object mask. And then run the refinement on another machine, which has a GUI. The refinement step only requires CPU.
> 
> Best, Yongzhi

Ok, Thanks a lot, I'll try it.
