### ISSUE TITLE
Score for Prediction and refinement

### ISSUE THREAD

**Issue by smoothumut** [suyz526/ZebraPose#26]
Hi Yongzhi,

I couldnt find a score for prediction and refinement in test_vivo.py . I think I am again missing something there. How do we calculate the score for both predictions and icp refinements?

Thanks in advance

**Comment by suyz526** [comment]
Hi,

Sorry, I cannot get your question well.

Our score is from the 2D detection, not related to the pose. If [this line](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/zebrapose/test_vivo.py#LL203C30-L203C36) reports an error. You can just replace it with `scores.append(1)` 

Best, 
Yongzhi

**Comment by smoothumut** [comment]
You are right, I wasnt clear. I wanted to mean that is it possible to get somehow a 3D Pose Score. 
If it is not, Is there any code in the repository to show rendered 2d image on real image so that we can compare how good estimation pose and refinement pose are.
thanks in advance

**Comment by suyz526** [comment]
Hi,

In this repository, we don't have the 3D pose score. To visualize the predicted pose, you can render the images using the bop toolkit with the generated .csv file.

**Comment by smoothumut** [comment]
Thank you very much Yongzhi, I will try that
I really deeply aprreciated.
Best Regards
