### ISSUE TITLE
visualization of pose estimation results

### ISSUE THREAD

**Issue by hrkita** [suyz526/ZebraPose#34]
Hello, I would like to ask where the implementation for loss curves and visualization of pose estimation results is located?

when i try to run python scripts/vis_est_poses.py，it encountered this error.
![question](https://github.com/suyz526/ZebraPose/assets/151819171/f3b552c1-e2da-46ff-9bc6-7c8a4de9925a)

I looked at the code, and there are options to choose between 'flat' and 'phong'. It seems that 'flat' may not require normals, but 'phong' appears to provide better visual effects.

How would you like to address this issue?

**Comment by suyz526** [comment]
Hello, 

There should be a folder called `tensorboard_logs` in the same path as the `checkpoints` folder. You can use tensorboard to visualize the data inside `tensorboard_logs`.

Regarding your second question, you can use Meshlab to generate a mesh with normal and replace the old mesh with this new one.

Best,
Yongzhi

**Comment by hrkita** [comment]
Hi Yongzhi,

Thank you for your prompt response!
 I've been able to visualize the loss curve.
 I haven't used Meshlab yet, but I'll make an effort to try out the method for the second question.

Best,
Joa

**Comment by hrkita** [comment]
Hi Yongzhi,

I tried to export normal information using MeshLab. These are the selected features.
![face normals](https://github.com/suyz526/ZebraPose/assets/151819171/d27e5c65-e38d-4152-8e52-b3291f801153)
And I selected this option when exporting the model.
![111](https://github.com/suyz526/ZebraPose/assets/151819171/4a2de885-378d-4cf6-9cd0-88f561f10619)
but when I run the program, it reports an error as follows:
![1212](https://github.com/suyz526/ZebraPose/assets/151819171/3708a12a-68ca-4580-ba8e-1affb6dd5aa1)

How would you like to address this issue?

Best,
Joa

**Comment by suyz526** [comment]
Let's try to not select the Binary encoding option.

**Comment by hrkita** [comment]
Great! It ran successfully and produced results!
I would like to ask if this warning needs to be addressed and whether the obtained results are correct?
![1234](https://github.com/suyz526/ZebraPose/assets/151819171/41e2ee6a-6e19-4e5d-b666-50a74a594cb0)
![24516](https://github.com/suyz526/ZebraPose/assets/151819171/c7c30492-9b7c-4dd8-bf7e-995432e26f4c)

Best,
Joa

**Comment by SimoneCortinovis97** [comment]
Hi, I try to run `python scripts/vis_est_poses.py` for the visualization of pose estimation results. It ran successfully, but the outputs images don't show the pose estimation:

```
(zebrapose) simoc@IITICB002LW012:~/ZebraPose/bop_toolkit$ python scripts/vis_est_poses.py 
3/1|13:06:11: Processing: zebrapose_lmo-test.csv
vispy uses app: egl, gl: gl2
3/1|13:06:12: Loading 3D model of object 1...
3/1|13:06:12: Loading 3D model of object 5...
3/1|13:06:12: Loading 3D model of object 6...
3/1|13:06:12: Loading 3D model of object 8...
3/1|13:06:12: Loading 3D model of object 9...
3/1|13:06:12: Loading 3D model of object 10...
3/1|13:06:12: Loading 3D model of object 11...
3/1|13:06:12: Loading 3D model of object 12...
3/1|13:06:12: Loading pose estimates...
3/1|13:06:12: Organizing pose estimates...
3/1|13:06:13: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 3
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
WARNING: Value provided for 'a_normal', but this variable was not found in the shader program.
WARNING: Value provided for 'a_texcoord', but this variable was not found in the shader program.
3/1|13:06:16: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 62
3/1|13:06:19: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 107
3/1|13:06:22: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 166
3/1|13:06:25: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 254
3/1|13:06:28: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 342
3/1|13:06:31: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 434
3/1|13:06:34: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 480
3/1|13:06:37: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 549
3/1|13:06:40: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 649
3/1|13:06:43: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 737
3/1|13:06:47: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 770
3/1|13:06:50: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 809
3/1|13:06:53: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 883
3/1|13:06:56: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 942
3/1|13:06:58: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 1038
3/1|13:07:02: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 1107
3/1|13:07:05: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 178
3/1|13:07:07: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 611
3/1|13:07:10: Visualizing pose estimates - method: zebrapose, dataset: lmo, scene: 2, im: 840
3/1|13:07:12: Done.
```

![image](https://github.com/icub-tech-iit/project-jl2-camozzi/assets/102801843/23d8a0e4-b6d3-409a-baaf-4531582e9e00)

Am I missing something?

Thanks,
Simone
