### ISSUE TITLE
extract features from the ROI

### ISSUE THREAD

**Issue by hrkita** [suyz526/ZebraPose#35]
Hi,

I want to ask, after the Fcos detector obtains the results of Bboxes, how does the ResNet-34 network extract features from the ROI region of interest（e.g. ape）? Is this implemented by the pre-trained model in the `pretrained_backbone` folder?

Best,
Joa

**Comment by suyz526** [comment]
Hi Joa,

The dataloader will use the bounding box to extract the ROI, as implemented in [#bop_dataset_pytorch.py](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/zebrapose/bop_dataset_pytorch.py#L267C32-L267C36),

You just need to provide the path of the JSON file, which stores all bounding boxes, to the config file.

Best, 
Yongzhi

**Comment by hrkita** [comment]
I have already understood the code now, thank for your enthusiastic respons3 ^_^
