### ISSUE TITLE
loss for predicted binary coding

### ISSUE THREAD

**Issue by hrkita** [suyz526/ZebraPose#36]
Hi，

If I want to compare the entire mask to obtain a loss function, what part of the code do I need to modify? Or do I need to retrain the ResNet34 model?

 if predict_entire_mask:
                loss_m = maskLoss(pred_mask_prob, entire_masks)
            else:
                loss_m = maskLoss(pred_mask_prob, masks)

Best,
Joa

**Comment by suyz526** [comment]
If you set this [arg](https://github.com/suyz526/ZebraPose/blob/06b53d2aab1f5e08ffc927b6c5a02e9913cb13f8/zebrapose/config/config_BOP_effnet/lmo/lmo_BOP_effnet_train.txt#L22) as True, the network will predict entire mask instead of visible mask.

**Comment by hrkita** [comment]
Okay, I will give it a try.Thanks!
